### ISSUE TITLE
Can not install/update apps FW. 2.3.8

### ISSUE THREAD

**Issue by Eweol** [Z-Wave-Me/zwave-smarthome#266]
Hey Guys,

I have the problem that I can't install apps with new FW 2.3.8 on my Raspberry Pi.
First time i thought that the libcurl4 of Ubuntu 18.04 is the Problem but I tested also on Ubuntu 16.04 on Raspberry Pi and there is also the failure. With FW 2.3.7 I can install apps on my Raspberry Pi on Ubuntu  16.04 same as on Ubuntu 18.04.
On Ubuntu 18.04 only need to use a fix from Z-Wave forum for libcurl3 / libcurl4 problem.
But I don't get it work with FW 2.3.8

**Comment by PoltoS** [comment]
This is certainly due to libcurl mismatch. Check during Z-Way start that it complains on missing lib for module modhttp

**Comment by Eweol** [comment]
So in Log this is the Failure

[2018-12-18 08:43:00.353] [E] [HTTP] Callback execution error: ReferenceError: installer is not defined
    at AutomationController.installModule (automation/classes/AutomationController.js:652:3)
    at ZAutomationAPIWebRequest._.extend.installModule (automation/ZAutomationAPIProvider.js:1039:29)
    at ZAutomationAPIWebRequest.ZAutomationWebRequest.handleRequest (automation/WebserverRequestRouter.js:259:35)
    at automation/WebserverRequestRouter.js:32:29
    at WebServer.document_root (automation/Webserver.js:35:11)

it is also the first entry from HTTP-Module and I don't get missing libs error in log

**Comment by PoltoS** [comment]
you get this error on Z-Way start

**Comment by Eweol** [comment]
I get this Error if I want to install or update an App on Startup I get no Errors

**Comment by martinscholz83** [comment]
Same problem here. Any workaround for this?

**Comment by PoltoS** [comment]
Please use Raspbian stretch and install the new v3.0.0 via .deb package. The new v3.0.0 is out!

**Comment by nebduj** [comment]
I'm on 3.0.0 with the same issue.  No issues on starting but get the same error when I try to install an app.

[2019-11-18 21:40:21.207] [E] [HTTP] Callback execution error: ReferenceError: installer is not defined
    at AutomationController.installModule (automation/classes/AutomationController.js:660:3)
    at ZAutomationAPIWebRequest._.extend.installModule (automation/ZAutomationAPIProvider.js:1042:29)
    at ZAutomationAPIWebRequest.ZAutomationWebRequest.handleRequest (automation/WebserverRequestRouter.js:263:35)
    at automation/WebserverRequestRouter.js:32:29
    at WebServer.document_root (automation/Webserver.js:35:11)

Firmware version	v3.0.0
UI version	1.10.1
Built date	18-07-2019 01:14:55
Capabilities:	SlM

**Comment by gilbi34** [comment]
Hello guys,

Same problem !!!! 
firmware : v3.0.4
Version UI: 1.10.2
built ;  20-01-2020 13:17:38
Raspbian  Buster V10
Mongoose : 6.4

Solution ???

**Comment by PoltoS** [comment]
New ticket https://github.com/Z-Wave-Me/zwave-smarthome/issues/275
