### ISSUE TITLE
[2.2.1-rc4] Hostmann Controls Thermostat Heat (Secure)

### ISSUE THREAD

**Issue by michapr** [Z-Wave-Me/zwave-smarthome#92]
Error mesage if updating setpoint via Smarthome UI:
```
[2016-01-20 11:34:54.490] [D] [zway] SETDATA devices.4.instances.0.commandClasses.67.data.1.setVal = 21.000000
[2016-01-20 11:34:54.492] [I] [zway] Adding job: ThermostatSetPoint Set
[2016-01-20 11:34:54.494] [D] [zway] Job 0x13 (ThermostatSetPoint Get): removing duplicate
[2016-01-20 11:34:54.497] [I] [zway] Node 4:0 CC ThermostatMode: Thermostat Mode 1 is not supported by device (modemask 0x0)
[2016-01-20 11:34:54.510] [I] [core] Notification: error (module): Error during perform command execution: Error: Invalid argument
[2016-01-20 11:34:54.546] [I] [core] Error: Invalid argument
    at Error (native)
    at t_vDev.(anonymous function).self.controller.devices.create.handler (automation/modules/ZWave/index.js:2069:60)
    at _.extend.performCommand (automation/classes/VirtualDevice.js:423:37)
    at ZAutomationAPIWebRequest._.extend.performVDevCommandFunc (automation/ZAutomationAPIProvider.js:288:60)
    at ZAutomationAPIWebRequest.handlerFunc (automation/ZAutomationAPIProvider.js:1977:52)
    at ZAutomationAPIWebRequest.ZAutomationWebRequest.handleRequest (automation/WebserverRequestRouter.js:258:41)
    at automation/WebserverRequestRouter.js:32:35
    at WebServer.document_root (automation/Webserver.js:29:11)
[2016-01-20 11:34:54.567] [I] [core] Notification: device-info (device-status): {"dev":"Hostmann Controls Thermostat Heat (4.0)","l":"21 °C"}
```
Value will not be updated at device

attached the unfiltered log (inclusion process)
[secure_thermostat_log.txt](https://github.com/Z-Wave-Me/zwave-smarthome/files/97305/secure_thermostat_log.txt)

**Comment by PoltoS** [comment]
According to NIF ThermostatMode is not supported, but controlled only. So no control possible,

**Comment by michapr** [comment]
ok, then seems SetPoint can be changed only while WakeUp - and will not be received after change.
Strange design ...

Thanks!
